### ISSUE TITLE
Quality

### ISSUE THREAD

**Issue by dmzoneill** [joaopsilva/binance-java-api#10]
Well.  Ive been doing a chunk of work for @jaggedsoft over on node and php.

Specifically
- unit testing
- code coverage
- documentation generate
- nightly builds across x versions with travis

If this is something you are interested in but have no time, im interested in this area.. . peoples commits will be auto validated for you then.. saves you testing stuff..

E.g:
https://github.com/jaggedsoft/php-binance-api

Ill set up a fork in your interested and create a pull request later on..

**Comment by joaopsilva** [comment]
Hi @dmzoneill , that sounds very interesting, can you make the contributions to https://github.com/binance-exchange/binance-java-api instead? That's where this project is being officially maintained. Thanks!

**Comment by dmzoneill** [comment]
@joaopsilva 

Im away till sunday.. grand fathers 90th.
In the mean time

Could you setup a 
- Travis account + add the project
- codacy for coding standards
- optionally
- codecov for coverage
- coveralls for coverage

Do you have any preference for the java unit testing library?
