### ISSUE TITLE
missing api/v1/exchangeInfo

### ISSUE THREAD

**Issue by abiemann** [joaopsilva/binance-java-api#11]
the api/v1/exchangeInfo API is missing in BinanceApiService.java

**Comment by abiemann** [comment]
documented at https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

**Comment by joaopsilva** [comment]
Hi @abiemann , please refer to the updated version of this library at https://github.com/binance-exchange/binance-java-api, where that API is available.
